### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by JVerstry** [icflorescu/openshift-cartridge-nodejs#16]
When I push my code, I get: 

```
remote: TypeError: Cannot read property 'start' of undefined
remote:     at [eval]:1:69
remote:     at Object.exports.runInThisContext (vm.js:54:17)
remote:     at Object.<anonymous> ([eval]-wrapper:6:22)
remote:     at Module._compile (module.js:425:26)
remote:     at node.js:589:27
remote:     at doNTCallback0 (node.js:430:9)
remote:     at process._tickCallback (node.js:359:13)
remote: [eval]:1
remote: var package = require("./package.json"); console.log(package.scripts.start);
```

I have create a dummy "start" in my package.json, but it did not solve the issue.

**Comment by AlexChesters** [comment]
@JVerstry can you post your `package.json`?

You should have something like this:

``` json
{
  "scripts": {
    "start": "node server.js"
  }
}
```

I'm assuming what you actually have is something like this:

``` json
{
  "start": "node server.js"
}
```

**Comment by icflorescu** [comment]
If `package.json` was correctly formatted, this may have been related to #17.

@JVerstry can you please try to create your application again?

**Comment by JVerstry** [comment]
I had:

```
"scripts": {
    "start": "node server.js"
}
```

I recreated the cartridge and the issue disappeared. Problem solved as far as I am concerned.

**Comment by icflorescu** [comment]
Great!
