### ISSUE TITLE
Failed to execute: 'control start' for ...

### ISSUE THREAD

**Issue by itsfolf** [icflorescu/openshift-cartridge-nodejs#70]
When I try to deploy or start my app I get this error:

```
DL is deprecated, please use Fiddle
Starting Node.js application...
Failed to execute: 'control start' for /var/lib/openshift/57e71d342d5271b2ee0000e3/nodejs
```

**Comment by itsfolf** [comment]
nodejs.log:

```
tarting 4 workers...
Application worker 55025 started...
Application worker 55036 started...
Application worker 55024 started...
Application worker 55037 started...
Got SIGTERM, stopping workers...
All workers stopped, exiting.
nohup: failed to run command `undefined': No such file or directory
nohup: failed to run command `undefined': No such file or directory
nohup: failed to run command `undefined': No such file or directory
nohup: failed to run command `undefined': No such file or directory
nohup: failed to run command `undefined': No such file or directory
```

**Comment by itsfolf** [comment]
Anyway, found it.
I forgot to set start script in package.json

**Comment by itsfolf** [comment]
Nop, no I'm getting

```
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at Object.<anonymous> (/var/lib/openshift/57e71d342d5271b2ee0000e3/app-root/runtime/repo/index.js:12:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

**Comment by BenWildeman** [comment]
"EADDRINUSE" means that the port you're trying to bind to is already in use

**Comment by icflorescu** [comment]
Please refer to [Before raising issues](https://github.com/icflorescu/openshift-cartridge-nodejs#before-raising-issues) note in the README.
